-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-25 22:55:58 COT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cuentas (
                         servicio_id     NUMBER NOT NULL,
                         habitaciones_id NUMBER NOT NULL
);

ALTER TABLE cuentas ADD CONSTRAINT cuentas_pk PRIMARY KEY ( servicio_id,
                                                            habitaciones_id );

CREATE TABLE habitaciones (
                              id         NUMBER NOT NULL,
                              numero     NUMBER NOT NULL,
                              disponible VARCHAR2(15),
                              reserva_id NUMBER NOT NULL,
                              hoteles_id NUMBER NOT NULL
);

ALTER TABLE habitaciones
    ADD CHECK ( disponible IN ( 'NO', 'SI' ) );

ALTER TABLE habitaciones ADD CONSTRAINT habitaciones_pk PRIMARY KEY ( id );

CREATE TABLE hoteles (
                         id     NUMBER NOT NULL,
                         nombre VARCHAR2(50),
                         nit    NUMBER NOT NULL
);

ALTER TABLE hoteles ADD CONSTRAINT hoteles_pk PRIMARY KEY ( id );

CREATE TABLE ocupadas (
                          habitaciones_id NUMBER NOT NULL,
                          usuarios_id     NUMBER NOT NULL
);

ALTER TABLE ocupadas ADD CONSTRAINT ocupadas_pk PRIMARY KEY ( habitaciones_id,
                                                              usuarios_id );

CREATE TABLE planes_consumo (
                                id         NUMBER NOT NULL,
                                nombre     VARCHAR2(50),
                                hoteles_id NUMBER NOT NULL
);

ALTER TABLE planes_consumo ADD CONSTRAINT planes_consumo_pk PRIMARY KEY ( id );

CREATE TABLE reservas (
                          id            NUMBER NOT NULL,
                          hora_reserva  VARCHAR2(50),
                          fecha_inicial DATE,
                          fecha_final   DATE
);

ALTER TABLE reservas ADD CONSTRAINT reservas_pk PRIMARY KEY ( id );

CREATE TABLE servicios (
                           id                       NUMBER NOT NULL,
                           horario_servicio_inicial VARCHAR2(50),
                           horario_servicio_final   VARCHAR2(50),
                           tipo_servicio_id         NUMBER NOT NULL,
                           reserva_id               NUMBER NOT NULL
);

ALTER TABLE servicios ADD CONSTRAINT servicios_pk PRIMARY KEY ( id );

CREATE TABLE tipos_habitaciones (
                                    id         NUMBER NOT NULL,
                                    tipo       VARCHAR2(55),
                                    capacidad  VARCHAR2(15),
                                    hoteles_id NUMBER NOT NULL
);

ALTER TABLE tipos_habitaciones
    ADD CHECK ( tipo IN ( 'LARGA_ESTADIA', 'PROMOCION', 'TIEMPO_COMPARTIDO', 'TODO_INCLUIDO' ) );

ALTER TABLE tipos_habitaciones ADD CONSTRAINT tipos_habitaciones_pk PRIMARY KEY ( id );

CREATE TABLE tipos_servicios (
                                 id     NUMBER NOT NULL,
                                 nombre VARCHAR2(50)
);

ALTER TABLE tipos_servicios ADD CONSTRAINT tipos_servicios_pk PRIMARY KEY ( id );

CREATE TABLE usuarios (
                          id               NUMBER NOT NULL,
                          nombre           VARCHAR2(50),
                          tipo_documento   VARCHAR2(25),
                          numero_documento NUMBER,
                          rol              VARCHAR2(25),
                          correo           VARCHAR2(30)
);

ALTER TABLE usuarios
    ADD CHECK ( tipo_documento IN ( 'CC', 'CE', 'NIT', 'PASAPORTE' ) );

ALTER TABLE usuarios
    ADD CHECK ( rol IN ( 'ADMINISTRADOR', 'CLIENTE', 'EMPLEADO', 'GERENTE', 'RECEPCIONISTA' ) );

ALTER TABLE usuarios ADD CONSTRAINT usuarios_pk PRIMARY KEY ( id );

ALTER TABLE cuentas
    ADD CONSTRAINT cuentas_habitaciones_fk FOREIGN KEY ( habitaciones_id )
        REFERENCES habitaciones ( id );

ALTER TABLE cuentas
    ADD CONSTRAINT cuentas_servicios_fk FOREIGN KEY ( servicio_id )
        REFERENCES servicios ( id );

ALTER TABLE habitaciones
    ADD CONSTRAINT habitaciones_hoteles_fk FOREIGN KEY ( hoteles_id )
        REFERENCES hoteles ( id );

ALTER TABLE habitaciones
    ADD CONSTRAINT habitaciones_reservas_fk FOREIGN KEY ( reserva_id )
        REFERENCES reservas ( id );

ALTER TABLE ocupadas
    ADD CONSTRAINT ocupadas_habitaciones_fk FOREIGN KEY ( habitaciones_id )
        REFERENCES habitaciones ( id );

ALTER TABLE ocupadas
    ADD CONSTRAINT ocupadas_usuarios_fk FOREIGN KEY ( usuarios_id )
        REFERENCES usuarios ( id );

ALTER TABLE planes_consumo
    ADD CONSTRAINT planes_consumo_hoteles_fk FOREIGN KEY ( hoteles_id )
        REFERENCES hoteles ( id );

ALTER TABLE servicios
    ADD CONSTRAINT servicios_reservas_fk FOREIGN KEY ( reserva_id )
        REFERENCES reservas ( id );

ALTER TABLE servicios
    ADD CONSTRAINT servicios_tipos_servicios_fk FOREIGN KEY ( tipo_servicio_id )
        REFERENCES tipos_servicios ( id );

ALTER TABLE tipos_habitaciones
    ADD CONSTRAINT tipos_habitaciones_hoteles_fk FOREIGN KEY ( hoteles_id )
        REFERENCES hoteles ( id );

CREATE SEQUENCE hotel_andes_sequence START WITH 1 NOCACHE ORDER;